// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrzi40051LdSu1lv7WpZfeIetv6uO0sYE',
    appId: '1:876951052986:web:a10ca59194587666bf5883',
    messagingSenderId: '876951052986',
    projectId: 'ecoscan-47dc9',
    authDomain: 'ecoscan-47dc9.firebaseapp.com',
    storageBucket: 'ecoscan-47dc9.firebasestorage.app',
    measurementId: 'G-XKQEH3F15N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6qBt7gezRreohJ48OeduOkMDV6Nqpm80',
    appId: '1:876951052986:android:312828a075d90025bf5883',
    messagingSenderId: '876951052986',
    projectId: 'ecoscan-47dc9',
    storageBucket: 'ecoscan-47dc9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChHH9tzLAJTMXxO_qY6NgBNvyolUbo9O4',
    appId: '1:876951052986:ios:a06112af7967eb92bf5883',
    messagingSenderId: '876951052986',
    projectId: 'ecoscan-47dc9',
    storageBucket: 'ecoscan-47dc9.firebasestorage.app',
    iosBundleId: 'com.example.ecoscan',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChHH9tzLAJTMXxO_qY6NgBNvyolUbo9O4',
    appId: '1:876951052986:ios:a06112af7967eb92bf5883',
    messagingSenderId: '876951052986',
    projectId: 'ecoscan-47dc9',
    storageBucket: 'ecoscan-47dc9.firebasestorage.app',
    iosBundleId: 'com.example.ecoscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrzi40051LdSu1lv7WpZfeIetv6uO0sYE',
    appId: '1:876951052986:web:917d810d993dd15abf5883',
    messagingSenderId: '876951052986',
    projectId: 'ecoscan-47dc9',
    authDomain: 'ecoscan-47dc9.firebaseapp.com',
    storageBucket: 'ecoscan-47dc9.firebasestorage.app',
    measurementId: 'G-KW30XSG090',
  );
}
